// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7VVL3dIOZqAyiZSF4SxmlZh8GLoN-B8Y',
    appId: '1:267812379813:web:195ef40d74cbaa92e3814c',
    messagingSenderId: '267812379813',
    projectId: 'chat-app-f64a3',
    authDomain: 'chat-app-f64a3.firebaseapp.com',
    storageBucket: 'chat-app-f64a3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOBBVZuuAQIw4P7UB9dN0Aw4C6DA4_82k',
    appId: '1:267812379813:android:8fa878f65940afede3814c',
    messagingSenderId: '267812379813',
    projectId: 'chat-app-f64a3',
    storageBucket: 'chat-app-f64a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM2LadgX0SgfUq0Qvt-joCLr70CCVjL_U',
    appId: '1:267812379813:ios:507b91bf7939adeee3814c',
    messagingSenderId: '267812379813',
    projectId: 'chat-app-f64a3',
    storageBucket: 'chat-app-f64a3.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM2LadgX0SgfUq0Qvt-joCLr70CCVjL_U',
    appId: '1:267812379813:ios:507b91bf7939adeee3814c',
    messagingSenderId: '267812379813',
    projectId: 'chat-app-f64a3',
    storageBucket: 'chat-app-f64a3.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7VVL3dIOZqAyiZSF4SxmlZh8GLoN-B8Y',
    appId: '1:267812379813:web:8a97acc9cefd2a91e3814c',
    messagingSenderId: '267812379813',
    projectId: 'chat-app-f64a3',
    authDomain: 'chat-app-f64a3.firebaseapp.com',
    storageBucket: 'chat-app-f64a3.firebasestorage.app',
  );
}
